### PR TITLE
first_run_date: Handling string in raw tables. 

### PR DESCRIPTION
**Pull request by godelstheory**

### CODE REVIEW

**Comment by xluo-ds** [comment]
@godelstheory Hey, can you take a look at [STMO#79741](https://sql.telemetry.mozilla.org/queries/79741/source) and [STMO#77855](https://sql.telemetry.mozilla.org/queries/77855/source)? They are exactly the same. I feel like the first one might be off?

**Comment by godelstheory** [comment]
Ugh - didn't save redash query. Rewrote it and _saved_. Please review again. Thanks!

**Comment by godelstheory** [comment]
@xluo-ds Could you take another look. Thanks!

**Comment by xluo-ds** [comment]
apologies that I landed on it late. 
LGTM :)

**Review by xluo-ds — APPROVED** [review]

**Comment by wlach** [comment]
Hey y'all, don't forget to merge after approving a PR. I'll take care of it this time.

**Pull request merged**
