### PR TITLE
Add Firefox-iOS `tabs.cumulative_count` note to clarify description

### PR DESCRIPTION
**Pull request by travis79**

### CODE REVIEW

**Comment by irrationalagent** [comment]
Should we just change the description in the yaml file since its no longer accurate? https://github.com/mozilla-mobile/firefox-ios/blob/f1f0cd8be4a205e4902776356603e91830c6fac7/Client/metrics.yaml#L280

**Comment by travis79** [comment]
> Should we just change the description in the yaml file since its no longer accurate? [mozilla-mobile/firefox-ios@`f1f0cd8`/Client/metrics.yaml#L280](https://github.com/mozilla-mobile/firefox-ios/blob/f1f0cd8be4a205e4902776356603e91830c6fac7/Client/metrics.yaml#L280)

That's probably the best idea, this metric is just weird anyways.  There really wasn't a good way to count tabs per session when this was instrumented, so I was hoping that the whole metric could be retired in favor of a custom distribution.

**Review by wlach — CHANGES_REQUESTED** [review]
👍 for modifying the description. We can leave this open for now to make sure the task doesn't get lost.

**Comment by travis79** [comment]
Okay, I have opened this PR against Firefox-iOS to update the description, I'll close this in favor of that PR when it lands: https://github.com/mozilla-mobile/firefox-ios/pull/8410.

**Pull request closed without merging**
